/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.BorderLayout;

/**
 *
 * @author uriab
 */
public class DashboardAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public DashboardAdmin() {
        initComponents();
        Home p1 = new Home ();
        p1.setSize(1140,660);
        p1.setLocation(5,10);

        content.removeAll();
       content.add(p1, BorderLayout.CENTER);
       content.revalidate();
       content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rSButtonIconTwo1 = new RSMaterialComponent.RSButtonIconTwo();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        rSPanelMaterialImage1 = new RSMaterialComponent.RSPanelMaterialImage();
        jLabel2 = new javax.swing.JLabel();
        rSButtonMaterialIconTwo1 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSButtonMaterialIconTwo2 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSButtonMaterialIconTwo3 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSButtonMaterialIconTwo4 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSButtonMaterialIconTwo5 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSButtonMaterialIconTwo6 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 35, 121));

        rSButtonIconTwo1.setBackground(new java.awt.Color(0, 35, 121));
        rSButtonIconTwo1.setHideActionText(true);
        rSButtonIconTwo1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MENU);
        rSButtonIconTwo1.setSizeIcon(50.0F);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEMA DE TICKETS");

        jButton1.setBackground(new java.awt.Color(204, 0, 51));
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(rSButtonIconTwo1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 743, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(255, 255, 255))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSButtonIconTwo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(15, 15, 15)))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 70));

        jPanel3.setForeground(new java.awt.Color(242, 242, 242));

        rSPanelMaterialImage1.setBackground(new java.awt.Color(242, 242, 242));
        rSPanelMaterialImage1.setBgShade(new java.awt.Color(242, 242, 242));
        rSPanelMaterialImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/View/images/logo-TND.png"))); // NOI18N

        jLabel2.setText("Admin");

        javax.swing.GroupLayout rSPanelMaterialImage1Layout = new javax.swing.GroupLayout(rSPanelMaterialImage1);
        rSPanelMaterialImage1.setLayout(rSPanelMaterialImage1Layout);
        rSPanelMaterialImage1Layout.setHorizontalGroup(
            rSPanelMaterialImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelMaterialImage1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        rSPanelMaterialImage1Layout.setVerticalGroup(
            rSPanelMaterialImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelMaterialImage1Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        rSButtonMaterialIconTwo1.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonMaterialIconTwo1.setText("INICIO");
        rSButtonMaterialIconTwo1.setBackgroundHover(new java.awt.Color(242, 242, 242));
        rSButtonMaterialIconTwo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rSButtonMaterialIconTwo1.setForegroundHover(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo1.setForegroundIcon(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo1.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo1.setForegroundText(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);
        rSButtonMaterialIconTwo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo1ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconTwo2.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonMaterialIconTwo2.setText("RUTA");
        rSButtonMaterialIconTwo2.setBackgroundHover(new java.awt.Color(242, 242, 242));
        rSButtonMaterialIconTwo2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rSButtonMaterialIconTwo2.setForegroundHover(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo2.setForegroundIcon(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo2.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo2.setForegroundText(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.TRAFFIC);
        rSButtonMaterialIconTwo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo2ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconTwo3.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonMaterialIconTwo3.setText("TRANSPORTE");
        rSButtonMaterialIconTwo3.setBackgroundHover(new java.awt.Color(242, 242, 242));
        rSButtonMaterialIconTwo3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rSButtonMaterialIconTwo3.setForegroundHover(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo3.setForegroundIcon(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo3.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo3.setForegroundText(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo3.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        rSButtonMaterialIconTwo3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.TRAIN);
        rSButtonMaterialIconTwo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo3ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconTwo4.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonMaterialIconTwo4.setText("TICKETS");
        rSButtonMaterialIconTwo4.setBackgroundHover(new java.awt.Color(242, 242, 242));
        rSButtonMaterialIconTwo4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rSButtonMaterialIconTwo4.setForegroundHover(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo4.setForegroundIcon(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo4.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo4.setForegroundText(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.STORAGE);
        rSButtonMaterialIconTwo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo4ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconTwo5.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonMaterialIconTwo5.setText("EMPLEADOS");
        rSButtonMaterialIconTwo5.setBackgroundHover(new java.awt.Color(242, 242, 242));
        rSButtonMaterialIconTwo5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rSButtonMaterialIconTwo5.setForegroundHover(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo5.setForegroundIcon(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo5.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo5.setForegroundText(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.WORK);
        rSButtonMaterialIconTwo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo5ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconTwo6.setBackground(new java.awt.Color(242, 242, 242));
        rSButtonMaterialIconTwo6.setText("USUARIOS");
        rSButtonMaterialIconTwo6.setBackgroundHover(new java.awt.Color(242, 242, 242));
        rSButtonMaterialIconTwo6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rSButtonMaterialIconTwo6.setForegroundHover(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo6.setForegroundIcon(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo6.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo6.setForegroundText(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo6.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.VERIFIED_USER);
        rSButtonMaterialIconTwo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rSButtonMaterialIconTwo1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(rSButtonMaterialIconTwo2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(rSButtonMaterialIconTwo4, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(rSButtonMaterialIconTwo5, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(rSButtonMaterialIconTwo6, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                .addGap(0, 19, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelMaterialImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(rSButtonMaterialIconTwo3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelMaterialImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMaterialIconTwo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMaterialIconTwo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMaterialIconTwo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMaterialIconTwo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMaterialIconTwo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMaterialIconTwo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 273, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 170, 740));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1160, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jPanel1.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 1160, 700));
        content.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1328, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMaterialIconTwo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo1ActionPerformed
       Home p1 = new Home ();
        p1.setSize(1140,660);
        p1.setLocation(5,10);

        content.removeAll();
       content.add(p1, BorderLayout.CENTER);
       content.revalidate();
       content.repaint();   
    }//GEN-LAST:event_rSButtonMaterialIconTwo1ActionPerformed

    private void rSButtonMaterialIconTwo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo4ActionPerformed
       Tickets p1 = new Tickets();
        p1.setSize(1140,660);
        p1.setLocation(5,10);

        content.removeAll();
       content.add(p1, BorderLayout.CENTER);
       content.revalidate();
       content.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconTwo4ActionPerformed

    private void rSButtonMaterialIconTwo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo3ActionPerformed
         Tranporte p1 = new Tranporte ();
        p1.setSize(1140,660);
        p1.setLocation(5,10);

        content.removeAll();
       content.add(p1, BorderLayout.CENTER);
       content.revalidate();
       content.repaint();
    }//GEN-LAST:event_rSButtonMaterialIconTwo3ActionPerformed

    private void rSButtonMaterialIconTwo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo2ActionPerformed
        ruta p1 = new ruta ();
        p1.setSize(1140,660);
        p1.setLocation(5,10);

        content.removeAll();
       content.add(p1, BorderLayout.CENTER);
       content.revalidate();
       content.repaint();
    }//GEN-LAST:event_rSButtonMaterialIconTwo2ActionPerformed

    private void rSButtonMaterialIconTwo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo5ActionPerformed
       
    }//GEN-LAST:event_rSButtonMaterialIconTwo5ActionPerformed

    private void rSButtonMaterialIconTwo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo6ActionPerformed
      
        PanelEmpleado p1 = new PanelEmpleado();
        p1.setSize(1140,660);
        p1.setLocation(5,10);
        content.removeAll();
       content.add(p1, BorderLayout.CENTER);
       content.revalidate();
       content.repaint();
       
    }//GEN-LAST:event_rSButtonMaterialIconTwo6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private RSMaterialComponent.RSButtonIconTwo rSButtonIconTwo1;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo1;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo2;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo3;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo4;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo5;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo6;
    private RSMaterialComponent.RSPanelMaterialImage rSPanelMaterialImage1;
    // End of variables declaration//GEN-END:variables
}
