/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author ricel
 */
public class ruta extends javax.swing.JPanel {

    /**
     * Creates new form ruta
     */
    public ruta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        rSPanelMaterialImage4 = new RSMaterialComponent.RSPanelMaterialImage();
        jPanel5 = new javax.swing.JPanel();
        rSPanelMaterialImage2 = new RSMaterialComponent.RSPanelMaterialImage();
        jPanel6 = new javax.swing.JPanel();
        rSPanelMaterialImage3 = new RSMaterialComponent.RSPanelMaterialImage();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        rSPanelMaterialImage4.setImagen(new javax.swing.ImageIcon(getClass().getResource("/View/images/MicrosoftTeams-image (10).png"))); // NOI18N

        javax.swing.GroupLayout rSPanelMaterialImage4Layout = new javax.swing.GroupLayout(rSPanelMaterialImage4);
        rSPanelMaterialImage4.setLayout(rSPanelMaterialImage4Layout);
        rSPanelMaterialImage4Layout.setHorizontalGroup(
            rSPanelMaterialImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );
        rSPanelMaterialImage4Layout.setVerticalGroup(
            rSPanelMaterialImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelMaterialImage4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(332, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(rSPanelMaterialImage4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("METRO", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        rSPanelMaterialImage2.setImagen(new javax.swing.ImageIcon(getClass().getResource("/View/images/MicrosoftTeams-image (12).png"))); // NOI18N

        javax.swing.GroupLayout rSPanelMaterialImage2Layout = new javax.swing.GroupLayout(rSPanelMaterialImage2);
        rSPanelMaterialImage2.setLayout(rSPanelMaterialImage2Layout);
        rSPanelMaterialImage2Layout.setHorizontalGroup(
            rSPanelMaterialImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 943, Short.MAX_VALUE)
        );
        rSPanelMaterialImage2Layout.setVerticalGroup(
            rSPanelMaterialImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelMaterialImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelMaterialImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("OMSA", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        rSPanelMaterialImage3.setImagen(new javax.swing.ImageIcon(getClass().getResource("/View/images/MicrosoftTeams-image (11).png"))); // NOI18N

        javax.swing.GroupLayout rSPanelMaterialImage3Layout = new javax.swing.GroupLayout(rSPanelMaterialImage3);
        rSPanelMaterialImage3.setLayout(rSPanelMaterialImage3Layout);
        rSPanelMaterialImage3Layout.setHorizontalGroup(
            rSPanelMaterialImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );
        rSPanelMaterialImage3Layout.setVerticalGroup(
            rSPanelMaterialImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelMaterialImage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(520, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelMaterialImage3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("TELEFERICO", jPanel6);

        add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 670));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private RSMaterialComponent.RSPanelMaterialImage rSPanelMaterialImage2;
    private RSMaterialComponent.RSPanelMaterialImage rSPanelMaterialImage3;
    private RSMaterialComponent.RSPanelMaterialImage rSPanelMaterialImage4;
    // End of variables declaration//GEN-END:variables
}
