/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author ricel
 */
public class Tranporte extends javax.swing.JPanel {

    /**
     * Creates new form Tranporte
     */
    public Tranporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        rSPanelMaterialImage3 = new RSMaterialComponent.RSPanelMaterialImage();
        rSPanelMaterialImage2 = new RSMaterialComponent.RSPanelMaterialImage();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        rSPanelMaterialImage4 = new RSMaterialComponent.RSPanelMaterialImage();
        rSPanelMaterialImage5 = new RSMaterialComponent.RSPanelMaterialImage();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        rSPanelMaterialImage1 = new RSMaterialComponent.RSPanelMaterialImage();
        rSPanelMaterialImage6 = new RSMaterialComponent.RSPanelMaterialImage();

        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("El Metro De Santo Domingo");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 16, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("El Metro de Santo Domingo  es el sistema de transporte público vial \nque sirve en la ciudad de Santo Domingo, capital de la República \nDominicana. En el año 2005, durante el mandato del presidente \nLeonel Fernández y con una inversión de más de 700 millones de \ndólares, se iniciaron los trabajos para la construcción del primer \nsistema de ferrocarril urbano subterráneo en Santo Domingo y \nen la República Dominicana.\n\nEl 27 de febrero de 2008 se realizó exitosamente el primer recorrido \noficial  con la presencia de las autoridades dominicanas y con la \nasesoría y supervisión de técnicos del Metro de Madrid.\n\nEl Metro de Santo Domingo cuenta con 2 líneas y 30 estaciones en \nfuncionamiento, cubriendo una longitud total de 48.5 kilómetros \n(Línea 1: 14.5km – Línea 2: 34km).");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 580, 420));

        rSPanelMaterialImage3.setImagen(new javax.swing.ImageIcon(getClass().getResource("/View/images/MicrosoftTeams-image (4).png"))); // NOI18N

        javax.swing.GroupLayout rSPanelMaterialImage3Layout = new javax.swing.GroupLayout(rSPanelMaterialImage3);
        rSPanelMaterialImage3.setLayout(rSPanelMaterialImage3Layout);
        rSPanelMaterialImage3Layout.setHorizontalGroup(
            rSPanelMaterialImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        rSPanelMaterialImage3Layout.setVerticalGroup(
            rSPanelMaterialImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jPanel2.add(rSPanelMaterialImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 430, 240));

        rSPanelMaterialImage2.setImagen(new javax.swing.ImageIcon(getClass().getResource("/View/images/metro-de-santo-domingo.jpg"))); // NOI18N

        javax.swing.GroupLayout rSPanelMaterialImage2Layout = new javax.swing.GroupLayout(rSPanelMaterialImage2);
        rSPanelMaterialImage2.setLayout(rSPanelMaterialImage2Layout);
        rSPanelMaterialImage2Layout.setHorizontalGroup(
            rSPanelMaterialImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        rSPanelMaterialImage2Layout.setVerticalGroup(
            rSPanelMaterialImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        jPanel2.add(rSPanelMaterialImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 430, 320));

        jTabbedPane2.addTab("Metro", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("El Teleferico De Santo Domingo");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 16, -1, -1));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("La obra del teleférico incluyó la construcción de cuatro estaciones \n(con intervención en sus entornos), el montaje del sistema \nelectromecánico con cinco plataformas, 36 torres de apoyo o \npilonas y el montaje del cable portante tractor. La justificación del \nproyecto estuvo determinada por la necesidad de una solución de\nmovilidad integral segura y digna para más de 287,000 \nciudadanos del Distrito Nacional y de los municipios de Santo \nDomingo Este y Santo Domingo Norte.\n\nEl sistema de cable aéreo brinda una solución factible para la \ninterconexión de las comunidades marginadas del Gran Santo \nDomingo –especialmente los barrios que atraviesa, que son \nGualey, Los Tres Brazos y Sabana Perdida–, favorece la \ntransformación urbana de los sectores de las márgenes de la \ncuenca del río Ozama y genera cohesión social a escala \nmetropolitana. Por otro lado, la integración física y tarifaria con el \nmetro de Santo Domingo y sus rutas alimentadoras representa un\nmodelo de gestión sostenible desde un punto de vista social, \neconómico y ambiental, con el que se estima un ahorro de \ntiempo y dinero para los usuarios de aproximadamente un 30%.\n");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 570, 550));

        rSPanelMaterialImage4.setImagen(new javax.swing.ImageIcon(getClass().getResource("/View/images/MicrosoftTeams-image (5).png"))); // NOI18N

        javax.swing.GroupLayout rSPanelMaterialImage4Layout = new javax.swing.GroupLayout(rSPanelMaterialImage4);
        rSPanelMaterialImage4.setLayout(rSPanelMaterialImage4Layout);
        rSPanelMaterialImage4Layout.setHorizontalGroup(
            rSPanelMaterialImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        rSPanelMaterialImage4Layout.setVerticalGroup(
            rSPanelMaterialImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        jPanel3.add(rSPanelMaterialImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 240, 360));

        rSPanelMaterialImage5.setImagen(new javax.swing.ImageIcon(getClass().getResource("/View/images/MicrosoftTeams-image (7).png"))); // NOI18N

        javax.swing.GroupLayout rSPanelMaterialImage5Layout = new javax.swing.GroupLayout(rSPanelMaterialImage5);
        rSPanelMaterialImage5.setLayout(rSPanelMaterialImage5Layout);
        rSPanelMaterialImage5Layout.setHorizontalGroup(
            rSPanelMaterialImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        rSPanelMaterialImage5Layout.setVerticalGroup(
            rSPanelMaterialImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        jPanel3.add(rSPanelMaterialImage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 420, 190));

        jTabbedPane2.addTab("Teleferico", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("La Oficina Metropolitana de Servicios de Autobuses (OMSA)");

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("La Oficina Metropolitana de Servicios de Autobuses (OMSA) fue creada \nmediante el Decreto Núm. 448- 97, del año 1997, como una dependencia \nde la Presidencia de la República, tomando en consideración que la \nmodernización del sistema de transporte en Santo Domingo ameritaba \nel establecimiento de una organización que garantizara el nivel de servicio, \nseguridad, limpieza y comodidad de los autobuses;\n\nCon la promulgación de la Ley 63-17: Movilidad, Transporte Terrestre, \nTránsito y Seguridad Vial de la República Dominicana, (deroga el Decreto \nNúm. 448 97 de la creación de la OMSA) y en su artículo No. 356, dispone \nque la institución pasara a ser reformada en empresa pública o mixta \npública-privada prestadora de servicios nacionales de transporte.\n\nTiene como propósito dar el servicio de preparación, mantenimiento, \nreparación y despacho de la flota de autobuses de transporte público de \nla ciudad de Santo Domingo, utilizando el patrimonio y el personal de la \nanterior Oficina Nacional de Transporte Terrestre, suprimida mediante el \nDecreto de creación de la OMSA.");
        jScrollPane3.setViewportView(jTextArea3);

        rSPanelMaterialImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/View/images/MicrosoftTeams-image (8).png"))); // NOI18N

        javax.swing.GroupLayout rSPanelMaterialImage1Layout = new javax.swing.GroupLayout(rSPanelMaterialImage1);
        rSPanelMaterialImage1.setLayout(rSPanelMaterialImage1Layout);
        rSPanelMaterialImage1Layout.setHorizontalGroup(
            rSPanelMaterialImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );
        rSPanelMaterialImage1Layout.setVerticalGroup(
            rSPanelMaterialImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );

        rSPanelMaterialImage6.setImagen(new javax.swing.ImageIcon(getClass().getResource("/View/images/MicrosoftTeams-image (9).png"))); // NOI18N

        javax.swing.GroupLayout rSPanelMaterialImage6Layout = new javax.swing.GroupLayout(rSPanelMaterialImage6);
        rSPanelMaterialImage6.setLayout(rSPanelMaterialImage6Layout);
        rSPanelMaterialImage6Layout.setHorizontalGroup(
            rSPanelMaterialImage6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );
        rSPanelMaterialImage6Layout.setVerticalGroup(
            rSPanelMaterialImage6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jLabel3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSPanelMaterialImage6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rSPanelMaterialImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rSPanelMaterialImage6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(rSPanelMaterialImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("OMSA", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private RSMaterialComponent.RSPanelMaterialImage rSPanelMaterialImage1;
    private RSMaterialComponent.RSPanelMaterialImage rSPanelMaterialImage2;
    private RSMaterialComponent.RSPanelMaterialImage rSPanelMaterialImage3;
    private RSMaterialComponent.RSPanelMaterialImage rSPanelMaterialImage4;
    private RSMaterialComponent.RSPanelMaterialImage rSPanelMaterialImage5;
    private RSMaterialComponent.RSPanelMaterialImage rSPanelMaterialImage6;
    // End of variables declaration//GEN-END:variables
}
